version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/src
      - ./.env:/var/www/html/.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
